### ISSUE TITLE
Question: is this module aimed to create h&s on a multi account environment?

### ISSUE THREAD

**Issue by drAlberT** [aws-ia/terraform-aws-network-hubandspoke#17]
From the documentation it's not clear to me if I can leverage this module on different account in order to implement, for example, a centralized account with VPC endpoints shared among many spokes accounts...

Thanks in advance.

**Comment by pablo19sc** [comment]
Hi! The idea for now is to keep the TGW and central VPCs in the same AWS Account. The Spoke VPC piece in the module only asks for VPC IDs and TGW attachments (it does not create them) as it supposes these VPCs are handled in other AWS Accounts - we suggest using our [VPC module](https://registry.terraform.io/modules/aws-ia/vpc/aws/latest) for that.
