### ISSUE TITLE
Example to showcase the use of spoke VPC variable inside the module

### ISSUE THREAD

**Issue by joshis2020** [aws-ia/terraform-aws-network-hubandspoke#19]
Hi,

I was going through the examples [here](https://github.com/aws-ia/terraform-aws-network-hubandspoke/tree/hubspoke-module/examples) but I could not find an example showcasing the usage of spoke VPC variable. 

I understand that to manage the spoke VPCs and its subnet routing, the recommendation is to use the [AWS VPC module](https://registry.terraform.io/modules/aws-ia/vpc/aws/latest). But I am trying to understand the usage of the spoke VPC variable here via an example.

From the document, it says that "This variable is used to provide the Hub and Spoke module the necessary information about the Spoke VPCs created." But its still unclear why this information is needed. An example of the same would be of a great help! Thanks in advance.

**Comment by pablo19sc** [comment]
We have updated the module, and now the examples show how you can work with the spoke VPC variable - hopefully it's useful!
