### ISSUE TITLE
Allow passing tags as input to module

### ISSUE THREAD

**Issue by benbooth493** [aws-ia/terraform-aws-network-hubandspoke#20]
As it stands in v3.0.0 it isn't possible to add tags to the created resources.

**Comment by pablo19sc** [comment]
Hello! Sorry for the delay on this, I missed it somehow. @benbooth493 

Working in some bug fixes, I'll add this in the next release. Thanks for your feedback!

**Comment by pablo19sc** [comment]
Added global variable tags in https://github.com/aws-ia/terraform-aws-network-hubandspoke/pull/21. In addition, the current version enables adding tags at the Transit Gateway level (if created using the module), and Central VPCs.

**Comment by pablo19sc** [comment]
Added in new version (v3.0.1). Tell me if it works as you expect!
