### ISSUE TITLE
Egress VPC connect_to_public_natgw based on inspection VPC config (not egress VPC config)

### ISSUE THREAD

**Issue by robertpyke** [aws-ia/terraform-aws-network-hubandspoke#22]
Just sanity checking - is this a bug:

https://github.com/aws-ia/terraform-aws-network-hubandspoke/blob/main/locals.tf#L188C8-L188C8

```
connect_to_public_natgw                         = try(var.central_vpcs.inspection.subnets.public.nat_gateway_configuration, "all_azs") != "none" ? true : false
```

It's setting the egress vpc connect_to_public_natgw setting based on the value provided for the inspection subnet. That seems like a bug?

**Comment by pablo19sc** [comment]
Fixed in new version (v3.0.1). Tell me if it works as you expect!
