### ISSUE TITLE
Version of terraform-aws-networkfirewall is out-of-date

### ISSUE THREAD

**Issue by awarner-greshamtech** [aws-ia/terraform-aws-network-hubandspoke#23]
I see there has been some activity here recently around updating module versions @pablo19sc 

The version of terraform-aws-networkfirewall used by this module is quite old and is preventing use of AWS provider > 5.0.

https://github.com/aws-ia/terraform-aws-networkfirewall/blob/v0.0.2/modules/central_inspection_with_egress_routing/providers.tf

The latest version of terraform-aws-networkfirewall is v1.0.0 and supports  > 5.0

I am getting the impression I should sit tight and wait for this module to switch to using terraform-aws-networkfirewall v1.0.0.

Is that planned?

**Comment by pablo19sc** [comment]
Hi @awarner-greshamtech, let me work on updating the Network Firewall module version during this week - we were updating all the modules in parallel and for some reason we missed updating that.

**Comment by pablo19sc** [comment]
v3.0.2 out! Network Firewall module updated to v1.0.0. Tell me if anything is not working as expected.
